name: Support request
description: Inform the tech team about occurring problems and get help.
title: "[Support]: "
type: Support request
labels: ["task:support-request"]
#projects: ["octo-org/1", "octo-org/44"]
assignees:
  - pdaengeli
body:
  - type: markdown
    attributes:
      value: |
        ## Use this form to report problems.

        ---
        
  - type: dropdown
    id: support-area
    attributes:
      label: Choose area of support
      multiple: false
      options:
        - Transkribus upload
        - Transkribus document deletion
        - Transkribus export (TEI)
        - other
      default: 3
      
  - type: textarea
    id: problem-desc
    attributes:
      label: Description
      description: "Short description of the problem."
      placeholder: |
        …
      render: bash
    validations:
      required: true  
      
